# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88b03bda894925a48dd0c0c4048b86ac90b2eef3aa2ad9731f7bf14908bc8694a1415cc82d0b89b67f8a2eaaf931f8c932f5f2d47aed04956b365f20db6e9456

test:
  secret_key_base: 0abb7a8a5024c854e05cd9455ffb0970fabad6f593304a3eade787607fd2de91a29112ba7dcecad451b300d35dca9a17f1e2d03df70a000fa8c15346b9dc91f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
